# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
        - dependency-name: "redis"
        - dependency-name: "@typescript-eslint/eslint-plugin"
        - dependency-name: "eslint"
        - dependency-name: "zod"
        - dependency-name: "@types/node"
        - dependency-name: "marked"
        - dependency-name: "@types/marked"
        - dependency-name: "cross-env"
        - dependency-name: "undici"
        - dependency-name: "eslint-config-prettier"
        - dependency-name: "@typescript-eslint/parser"

