services:
  ssu-rag:
    build: .
    container_name: SSU_RAG
    ports:
      - "8888:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DOCKER_ENV=true
      - MILVUS_HOST=milvus
    volumes:
      - ./data:/app/data
    depends_on:
      - milvus
    networks:
      - ssu-rag-network

  milvus:
    image: milvusdb/milvus:v2.3.2
    container_name: milvus-standalone
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - milvus_data:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - etcd
      - minio
    networks:
      - ssu-rag-network

  attu:
    image: zilliz/attu:latest
    container_name: attu
    environment:
      - MILVUS_URL=milvus:19530
    ports:
      - "18000:3000"
    depends_on:
      - milvus
    networks:
      - ssu-rag-network

  frontend:
    image: node:18-alpine
    container_name: ssu-rag-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3001"
    command: sh -c "npm install && npm run dev -- --host --port 3001"
    environment:
      - NODE_ENV=development
    networks:
      - ssu-rag-network

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: milvus-etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
      - ssu-rag-network

  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: milvus-minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - minio_data:/data
    command: minio server /data
    ports:
      - "9001:9000"
      - "9010:9001"
    networks:
      - ssu-rag-network

volumes:
  milvus_data:
  etcd_data:
  minio_data:

networks:
  ssu-rag-network:
    driver: bridge
