[tool.basedpyright]
exclude = [
    ".coveragerc",
    "alembic.ini",
    "*.md",
    "docs/**",
    "tests/**"
]

[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 88

[tool.safety]
# Usar requirements.txt en lugar de pyproject.toml para dependencias

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--cov=app",
    "--cov-report=term-missing",
    "--cov-report=html",
    "--cov-fail-under=0",
    "-v"
]
