prompts:
  - "Act as a travel guide for {{location}}"
  - "I want you to act as a travel guide. I will write you my location and you will suggest a place to visit near my location. In some cases, I will also give you the type of places I will visit. You will also suggest me places of similar type that are close to my first location. My current location is {{location}}"

providers:
  - openai:gpt-4o
  - anthropic:messages:claude-3-7-sonnet-20250219

tests:
  - vars:
      location: "San Francisco"
  - vars:
      location: "Wyoming"
  - vars:
      location: "Kyoto"
  - vars:
      location: "Great Barrier Reef"
